### PR TITLE
Request bugs

### LINKED ISSUE #95: Fix Requests bug
There is a bug with requests that causes the approval count to display the get mixed up and display the approval account for the wrong request.

### PR DESCRIPTION
**Pull request by jpc20**
# Pull request checklist

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Current behavior

- When displaying requests, the approval count for each request was getting mixed up and we were showing the wrong number of votes for the requests.

## New behavior

- Changed numOfVotes in data from an array to an object so we could associate each vote count with the specific request id

## Other information

closes #95

### CODE REVIEW

File: src/ui/RequestContainer.vue [hunk 1]
```diff
@@ -84,7 +85,7 @@ export default {
   },
   data() {
     return {
-      numOfVotes: [],
+      numOfVotes: {},
```
Comment (jpc20) [inline src/ui/RequestContainer.vue:88]: I think the problem was that the vote counts were getting mixed up in the array, so hopefully switching to an object fixes the bug.

Comment (edmdc) [reply src/ui/RequestContainer.vue:88]: Haha, makes sense now that you point it out. Nice catch.
